#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Fenrir TTY screen reader
# By Chrys, Storm Dragon, and contributers.

import os, sys
import fenrirVersion

if not os.path.dirname(os.path.realpath(fenrirVersion.__file__)) in sys.path:
    sys.path.append(os.path.dirname(os.path.realpath(fenrirVersion.__file__)))

from core import fenrirManager

def main():
    app = fenrirManager.fenrirManager()
    app.proceed()
    del app

if __name__ == "__main__":
    main()     
