#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Fenrir TTY screen reader
# By Chrys, Storm Dragon, and contributers.

import os, sys, inspect
fenrirPath = os.path.dirname(os.path.realpath(os.path.abspath(inspect.getfile(inspect.currentframe()))))

if not fenrirPath in sys.path:
    sys.path.append(fenrirPath)

from fenrirscreenreader.core import fenrirManager
from daemonize import Daemonize

pidFile = "/run/fenrir.pid"

def main():
    app = fenrirManager.fenrirManager()
    app.proceed()
    del app

if __name__ == "__main__":
    # for debug in foreground
    #daemon = Daemonize(app="fenrir-daemon", pid=pidFile, action=main, foreground=True,chdir=fenrirPath)
    daemon = Daemonize(app="fenrir-daemon", pid=pidFile, action=main, chdir=fenrirPath)
    daemon.start()

