#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Fenrir TTY screen reader
# By Chrys, Storm Dragon, and contributers.

import os, sys, inspect
fenrirPath = os.path.dirname(os.path.realpath(os.path.abspath(inspect.getfile(inspect.currentframe()))))

if not fenrirPath in sys.path:
    sys.path.append(fenrirPath)

from fenrirscreenreader.core import fenrirManager

def main():
    app = fenrirManager.fenrirManager()
    app.proceed()
    del app

if __name__ == "__main__":
    main()     
